/**
 * authority-constitution.ts — Hard Rules for Authority Failure Behavior
 *
 * PURPOSE:
 * This module defines the CONSTITUTION for what happens when authority is absent.
 * It is the SINGLE SOURCE for "no authority = explicit error, no state progression."
 *
 * PRINCIPLES:
 * - Authority-owned facts: ONLY main process may produce these
 * - Forbidden fallback patterns: Renderer MUST NOT silently fall back when authority fails
 * - Authority failure contract: All authority failures surface as explicit errors
 *
 * ANTI-PATTERNS THIS CONSTITUTION BANS:
 * 1. `catch { setStage(...) }` — renderer catching errors and setting stage locally
 * 2. `if (!result.project) { setStage(...) }` — optimistic local stage updates
 * 3. `?? existingState` — using stale cached state when fresh authority state unavailable
 * 4. Silent IPC failure with local fallback — not surfacing main process errors
 * 5. Incomplete result assumption — treating partial results as complete
 *
 * RENDERER RULE (fundamental):
 * - Renderer is ONLY a consumer, NEVER a producer for core truths
 * - When authority is unavailable, renderer MUST surface the error, NOT substitute
 *
 * This file is the CONSTITUTION — it defines the rules, not the implementation.
 * Actual enforcement happens at IPC boundaries and orchestrator layer.
 */

// =============================================================================
// AUTHORITY-OWNED FACTS
// =============================================================================

/**
 * Facts that require MAIN process authority.
 *
 * These facts MUST only be produced by main process.
 * Any attempt to produce these in renderer must fail explicitly.
 *
 * RENDERER CONSUMER NOTE:
 * Renderer may READ these facts via IPC, but must NEVER:
 * - Write them to local state as if they were authoritative
 * - Use them to compute other "derived" facts locally
 * - Cache them and use cached version when IPC fails
 */
export const AuthorityOwnedFacts = {
  /**
   * Current workflow stage — derived by main from project snapshot
   * NEVER: renderer computing stage locally from partial state
   */
  STAGE: 'stage',

  /**
   * Blocked reason — computed by main's contract policy
   * NEVER: renderer inferring blocked reason from UI state
   */
  BLOCKED_REASON: 'blockedReason',

  /**
   * Resume eligibility — derived by main from progress board
   * NEVER: renderer deciding "canResume" from cached board state
   */
  RESUME_ELIGIBILITY: 'resumeEligibility',

  /**
   * Generation status — owned by main, represents in-flight generation
   * NEVER: renderer setting generationStatus locally in catch block
   */
  GENERATION_STATUS: 'generationStatus',

  /**
   * Script runtime state — built up by main's script generation
   * NEVER: renderer modifying scriptDraft/scriptProgressBoard locally
   */
  SCRIPT_RUNTIME_STATE: 'scriptRuntimeState',

  /**
   * Script progress board — maintained by main's batch observer
   * NEVER: renderer writing to progressBoard directly
   */
  PROGRESS_BOARD: 'progressBoard',

  /**
   * Failure resolution — created by main on generation failure
   * NEVER: renderer constructing failureResolution locally
   */
  FAILURE_RESOLUTION: 'failureResolution',

  /**
   * Failure history — accumulated by main across generations
   * NEVER: renderer managing failureHistory independently
   */
  FAILURE_HISTORY: 'failureHistory',

  /**
   * Formal facts — confirmed by main's formal fact handlers
   * NEVER: renderer declaring formal facts locally
   */
  FORMAL_FACTS: 'formalFacts',

  /**
   * Detailed outline blocks — generated by main
   * NEVER: renderer computing or modifying detailedOutlineBlocks locally
   */
  DETAILED_OUTLINE_BLOCKS: 'detailedOutlineBlocks',

  /**
   * Character drafts — generated by main
   * NEVER: renderer writing characterDrafts locally
   */
  CHARACTER_DRAFTS: 'characterDrafts',

  /**
   * Outline draft — generated by main
   * NEVER: renderer writing outlineDraft locally
   */
  OUTLINE_DRAFT: 'outlineDraft'
} as const

export type AuthorityOwnedFact = (typeof AuthorityOwnedFacts)[keyof typeof AuthorityOwnedFacts]

/**
 * Facts that renderer may read but must never produce or cache as authoritative.
 * This is a subset of AuthorityOwnedFacts focused on what renderer commonly accesses.
 */
export const RendererReadOnlyFacts: ReadonlyArray<AuthorityOwnedFact> = [
  AuthorityOwnedFacts.STAGE,
  AuthorityOwnedFacts.BLOCKED_REASON,
  AuthorityOwnedFacts.RESUME_ELIGIBILITY,
  AuthorityOwnedFacts.GENERATION_STATUS,
  AuthorityOwnedFacts.SCRIPT_RUNTIME_STATE,
  AuthorityOwnedFacts.PROGRESS_BOARD,
  AuthorityOwnedFacts.FAILURE_RESOLUTION,
  AuthorityOwnedFacts.FAILURE_HISTORY,
  AuthorityOwnedFacts.FORMAL_FACTS,
  AuthorityOwnedFacts.DETAILED_OUTLINE_BLOCKS,
  AuthorityOwnedFacts.CHARACTER_DRAFTS,
  AuthorityOwnedFacts.OUTLINE_DRAFT
] as const

// =============================================================================
// FORBIDDEN FALLBACK PATTERNS
// =============================================================================

/**
 * Fallback patterns that are FORBIDDEN when authority is unavailable.
 *
 * These patterns represent "silent substitution" —renderer substituting
 * its own judgment when authority fails. This is a constitutional violation.
 *
 * CONSTITUTIONAL RULE:
 * When any of these patterns would be triggered, instead:
 * 1. Surface the authority failure as an explicit error
 * 2. Do NOT progress business state
 * 3. Let the error bubble up to error boundary
 */
export const ForbiddenFallbackPatterns = {
  /**
   * FORBIDDEN: catch { setStage(...) }
   * Anti-pattern: renderer catches error and sets stage locally as fallback
   * Constitutional rule: errors must surface, not silently handle
   */
  CATCH_SET_STAGE: 'catch-setStage',

  /**
   * FORBIDDEN: if (!result.project) { setStage(...) }
   * Anti-pattern: renderer checks for result absence and updates stage optimistically
   * Constitutional rule: missing project is authority failure, must surface
   */
  MISSING_RESULT_OPTIMISTIC_STAGE: 'missing-result-optimistic-stage',

  /**
   * FORBIDDEN: ?? existingCachedState
   * Anti-pattern: using stale cached state when fresh authority state unavailable
   * Constitutional rule: stale state is not authority, must surface
   */
  STALE_CACHED_STATE_FALLBACK: 'stale-cached-state-fallback',

  /**
   * FORBIDDEN: Silently swallowing IPC errors and continuing
   * Anti-pattern: IPC call fails but renderer continues as if success
   * Constitutional rule: IPC failure is authority failure, must surface
   */
  SILENT_IPC_FAILURE: 'silent-ipc-failure',

  /**
   * FORBIDDEN: Treating incomplete result as complete
   * Anti-pattern: result has missing fields but code proceeds as if complete
   * Constitutional rule: incomplete result is authority failure, must surface
   */
  INCOMPLETE_RESULT_AS_COMPLETE: 'incomplete-result-as-complete',

  /**
   * FORBIDDEN: Fallback to "chat" stage when authority unclear
   * Anti-pattern: unclear authority state → default to chat
   * Constitutional rule: unclear authority must surface as error, not default
   */
  UNKNOWN_AUTHORITY_DEFAULT_CHAT: 'unknown-authority-default-chat',

  /**
   * FORBIDDEN: renderer computing derived facts from cached data
   * Anti-pattern: renderer computes "canResume" from cached board
   * Constitutional rule: derived facts require fresh authority computation
   */
  RENDERER_COMPUTING_DERIVED_FACTS: 'renderer-computing-derived-facts',

  /**
   * FORBIDDEN: Silent retry on IPC failure
   * Anti-pattern: IPC fails → retry silently → proceed if succeeds
   * Constitutional rule: IPC failure must surface, not silently retry
   */
  SILENT_IPC_RETRY: 'silent-ipc-retry'
} as const

export type ForbiddenFallbackPattern =
  (typeof ForbiddenFallbackPatterns)[keyof typeof ForbiddenFallbackPatterns]

/**
 * Error codes for forbidden fallback pattern violations.
 * Used to identify what pattern was violated in error reporting.
 */
export const ForbiddenFallbackErrorCodes = {
  [ForbiddenFallbackPatterns.CATCH_SET_STAGE]: 'AUTHORITY_CONSTITUTION_CATCH_SET_STAGE',
  [ForbiddenFallbackPatterns.MISSING_RESULT_OPTIMISTIC_STAGE]:
    'AUTHORITY_CONSTITUTION_MISSING_RESULT',
  [ForbiddenFallbackPatterns.STALE_CACHED_STATE_FALLBACK]: 'AUTHORITY_CONSTITUTION_STALE_STATE',
  [ForbiddenFallbackPatterns.SILENT_IPC_FAILURE]: 'AUTHORITY_CONSTITUTION_IPC_FAILURE',
  [ForbiddenFallbackPatterns.INCOMPLETE_RESULT_AS_COMPLETE]:
    'AUTHORITY_CONSTITUTION_INCOMPLETE_RESULT',
  [ForbiddenFallbackPatterns.UNKNOWN_AUTHORITY_DEFAULT_CHAT]:
    'AUTHORITY_CONSTITUTION_UNKNOWN_DEFAULT',
  [ForbiddenFallbackPatterns.RENDERER_COMPUTING_DERIVED_FACTS]:
    'AUTHORITY_CONSTITUTION_RENDERER_DERIVED',
  [ForbiddenFallbackPatterns.SILENT_IPC_RETRY]: 'AUTHORITY_CONSTITUTION_IPC_RETRY'
} as const

// =============================================================================
// AUTHORITY FAILURE CONTRACT
// =============================================================================

/**
 * Types of authority failure that require explicit error surfacing.
 * Each failure type has a specific contract for how it must be handled.
 */
export const AuthorityFailureType = {
  /**
   * IPC call to main process failed entirely
   * Contract: Surface as error, do not retry silently, do not use cached state
   */
  IPC_FAILURE: 'ipc_failure',

  /**
   * Project does not exist or cannot be loaded
   * Contract: Surface as error with PROJECT_NOT_FOUND code, no optimistic fallback
   */
  PROJECT_MISSING: 'project_missing',

  /**
   * Authority result is null/undefined
   * Contract: Surface as error, do not assume "no content" = "empty but valid"
   */
  AUTHORITY_RESULT_NULL: 'authority_result_null',

  /**
   * Authority result is missing required fields
   * Contract: Surface as error with INCOMPLETE_RESULT code, do not fill defaults
   */
  INCOMPLETE_RESULT: 'incomplete_result',

  /**
   * Result is stale (timestamp too old)
   * Contract: Surface as warning if displayable, error if blocking
   */
  STALE_RESULT: 'stale_result',

  /**
   * Main process threw an exception
   * Contract: Surface the exception as error, do not catch and continue
   */
  MAIN_EXCEPTION: 'main_exception',

  /**
   * Orchestrator bypass detected — live path not followed
   * Contract: Surface as error, do not allow旁路 to become defacto
   */
  ORCHESTRATOR_BYPASS: 'orchestrator_bypass'
} as const

export type AuthorityFailureTypeValue =
  (typeof AuthorityFailureType)[keyof typeof AuthorityFailureType]

/**
 * Authority failure error — thrown when authority check fails.
 * This is the explicit error surface for authority violations.
 */
export class AuthorityFailureError extends Error {
  readonly failureType: AuthorityFailureTypeValue
  readonly fact: AuthorityOwnedFact
  readonly context: string
  readonly originalError?: unknown

  constructor(
    failureType: AuthorityFailureTypeValue,
    fact: AuthorityOwnedFact,
    context: string,
    originalError?: unknown
  ) {
    const errorCode = `AUTHORITY_FAILURE_${failureType.toUpperCase()}`
    const message = `[${errorCode}] Authority failure for "${fact}": ${context}`
    super(message)
    this.name = 'AuthorityFailureError'
    this.failureType = failureType
    this.fact = fact
    this.context = context
    this.originalError = originalError
  }
}

/**
 * Result of an authority check — either success or explicit failure.
 * Used to enforce "no silent fallback" at IPC boundaries.
 */
export type AuthorityCheckResult<T> =
  | { ok: true; value: T }
  | { ok: false; failure: AuthorityFailureError }

/**
 * Create a successful authority check result.
 */
export function authorityOk<T>(value: T): AuthorityCheckResult<T> {
  return { ok: true, value }
}

/**
 * Create a failed authority check result.
 */
export function authorityFail(
  failureType: AuthorityFailureTypeValue,
  fact: AuthorityOwnedFact,
  context: string,
  originalError?: unknown
): AuthorityCheckResult<never> {
  return {
    ok: false,
    failure: new AuthorityFailureError(failureType, fact, context, originalError)
  }
}

/**
 * Assert that an authority check passed, throwing if it failed.
 * Use at IPC boundaries to enforce explicit error surfacing.
 */
export function assertAuthorityCheck<T>(result: AuthorityCheckResult<T>, context = ''): T {
  if (!result.ok) {
    if (context) {
      result.failure.message = `[${context}] ${result.failure.message}`
    }
    throw result.failure
  }
  return result.value
}

// =============================================================================
// AUTHORITY VALIDATION HELPERS
// =============================================================================

/**
 * Check if a fact is authority-owned (requires MAIN process authority).
 */
export function isAuthorityOwnedFact(fact: string): fact is AuthorityOwnedFact {
  return Object.values(AuthorityOwnedFacts).includes(fact as AuthorityOwnedFact)
}

/**
 * Validate that a value is not null/undefined.
 * Returns authority failure result if null/undefined.
 */
export function requireAuthorityValue<T>(
  value: T | null | undefined,
  fact: AuthorityOwnedFact,
  context: string
): AuthorityCheckResult<T> {
  if (value === null || value === undefined) {
    return authorityFail(AuthorityFailureType.AUTHORITY_RESULT_NULL, fact, context)
  }
  return authorityOk(value)
}

/**
 * Validate that an object has all required fields.
 * Returns authority failure result if any field is missing.
 */
export function requireAuthorityFields<T extends object>(
  obj: Partial<T> | null | undefined,
  fact: AuthorityOwnedFact,
  context: string,
  requiredFields: (keyof T)[]
): AuthorityCheckResult<T> {
  if (obj === null || obj === undefined) {
    return authorityFail(AuthorityFailureType.AUTHORITY_RESULT_NULL, fact, context)
  }

  const missingFields = requiredFields.filter((field) => !(field in obj))
  if (missingFields.length > 0) {
    return authorityFail(
      AuthorityFailureType.INCOMPLETE_RESULT,
      fact,
      `${context}: missing fields [${missingFields.join(', ')}]`
    )
  }

  return authorityOk(obj as T)
}

/**
 * Validate that an IPC result is not a forbidden fallback pattern.
 * Throws AuthorityFailureError if a forbidden pattern is detected.
 */
export function enforceNoForbiddenFallback(
  pattern: ForbiddenFallbackPattern,
  context: string,
  originalError?: unknown
): void {
  const fact = detectForbiddenFallbackFact(pattern)
  throw new AuthorityFailureError(
    AuthorityFailureType.IPC_FAILURE,
    fact,
    `Forbidden fallback pattern detected: ${pattern} — ${context}`,
    originalError
  )
}

/**
 * Detect which authority-owned fact is at risk from a forbidden fallback pattern.
 * Used for error reporting when a forbidden pattern is detected.
 */
function detectForbiddenFallbackFact(pattern: ForbiddenFallbackPattern): AuthorityOwnedFact {
  switch (pattern) {
    case ForbiddenFallbackPatterns.CATCH_SET_STAGE:
    case ForbiddenFallbackPatterns.UNKNOWN_AUTHORITY_DEFAULT_CHAT:
      return AuthorityOwnedFacts.STAGE
    case ForbiddenFallbackPatterns.MISSING_RESULT_OPTIMISTIC_STAGE:
      return AuthorityOwnedFacts.STAGE
    case ForbiddenFallbackPatterns.RENDERER_COMPUTING_DERIVED_FACTS:
      return AuthorityOwnedFacts.RESUME_ELIGIBILITY
    case ForbiddenFallbackPatterns.STALE_CACHED_STATE_FALLBACK:
      return AuthorityOwnedFacts.SCRIPT_RUNTIME_STATE
    default:
      return AuthorityOwnedFacts.GENERATION_STATUS
  }
}

// =============================================================================
// TYPE GUARDS FOR RENDERER
// =============================================================================

/**
 * Type guard: returns true if running in renderer process.
 * Used to enforce renderer-only constraints at runtime.
 *
 * NOTE: This is a best-effort check. The constitutional rules
 * must be enforced by code structure, not just runtime checks.
 */
export function isRendererProcess(): boolean {
  // In Electron, renderer process has access to window.api but not direct Node
  // This is a structural check, not a security guarantee
  return (
    typeof window !== 'undefined' &&
    typeof (window as unknown as { api?: unknown }).api !== 'undefined'
  )
}

/**
 * Assert that code is running in renderer process.
 * Throws if called in main process (which would indicate a code smell).
 */
export function assertRendererProcess(): void {
  if (!isRendererProcess()) {
    throw new Error(
      '[AuthorityConstitution] CODE SMELL: Renderer-only constraint called outside renderer process'
    )
  }
}

/**
 * Assert that a fact is being read (not written) by renderer.
 * This is a documentation assertion — actual enforcement happens at IPC boundary.
 */
export function assertRendererReadOnly(fact: AuthorityOwnedFact): void {
  if (!RendererReadOnlyFacts.includes(fact)) {
    throw new Error(
      `[AuthorityConstitution] "${fact}" is not in RendererReadOnlyFacts — review authority constitution`
    )
  }
}
